using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Proxos.Generator.Registration;

/// <summary>
/// Incremental Source Generator que escaneia o assembly em compile-time e gera
/// um método <c>AddProxosGenerated()</c> com registro estático de todos os handlers.
/// Elimina o assembly scanning em runtime.
/// </summary>
[Generator]
public sealed class HandlerRegistrationGenerator : IIncrementalGenerator
{
    private const string RequestHandlerInterface = "Proxos.IRequestHandler";
    private const string NotificationHandlerInterface = "Proxos.INotificationHandler";
    private const string StreamRequestHandlerInterface = "Proxos.IStreamRequestHandler";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Pipeline: coleta classes concretas que implementam interfaces do Proxos
        var handlerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cls
                    && cls.BaseList is not null
                    && !cls.Modifiers.Any(m => m.ValueText == "abstract"),
                transform: static (ctx, ct) => GetHandlerInfo(ctx, ct))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(handlerClasses, static (spc, handlers) =>
            GenerateSource(spc, handlers!));
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.Node is not ClassDeclarationSyntax classDecl)
            return null;

        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract || symbol.IsGenericType)
            return null;

        var handlers = new List<HandlerEntry>();

        foreach (var iface in symbol.AllInterfaces)
        {
            ct.ThrowIfCancellationRequested();

            var fullName = iface.OriginalDefinition.ToDisplayString();

            if (fullName.StartsWith(RequestHandlerInterface) && iface.TypeArguments.Length == 2)
            {
                handlers.Add(new HandlerEntry(
                    HandlerKind.Request,
                    symbol.ToDisplayString(),
                    iface.ToDisplayString(),
                    iface.TypeArguments[0].ToDisplayString(),
                    iface.TypeArguments[1].ToDisplayString()));
            }
            else if (fullName.StartsWith(NotificationHandlerInterface) && iface.TypeArguments.Length == 1)
            {
                handlers.Add(new HandlerEntry(
                    HandlerKind.Notification,
                    symbol.ToDisplayString(),
                    iface.ToDisplayString(),
                    iface.TypeArguments[0].ToDisplayString(),
                    null));
            }
            else if (fullName.StartsWith(StreamRequestHandlerInterface) && iface.TypeArguments.Length == 2)
            {
                handlers.Add(new HandlerEntry(
                    HandlerKind.Stream,
                    symbol.ToDisplayString(),
                    iface.ToDisplayString(),
                    iface.TypeArguments[0].ToDisplayString(),
                    iface.TypeArguments[1].ToDisplayString()));
            }
        }

        if (handlers.Count == 0)
            return null;

        return new HandlerInfo(symbol.ToDisplayString(), handlers);
    }

    private static void GenerateSource(
        SourceProductionContext context,
        ImmutableArray<HandlerInfo> handlers)
    {
        if (handlers.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Proxos.Generator />");
        sb.AppendLine("// Gerado em compile-time — não edite manualmente.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace ProxosGenerated;");
        sb.AppendLine();
        sb.AppendLine("[EditorBrowsable(EditorBrowsableState.Never)]");
        sb.AppendLine("public static class ProxosGeneratedExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registra todos os handlers descobertos em compile-time.");
        sb.AppendLine("    /// Substitui o assembly scanning em runtime — startup instantâneo.");
        sb.AppendLine("    /// Deve ser chamado após <c>AddProxos()</c>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddProxosGenerated(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        var wrapperRegistry = global::Proxos.ProxosRegistrar.GetRegistry(services)");
        sb.AppendLine("            ?? throw new global::System.InvalidOperationException(");
        sb.AppendLine("                \"AddProxosGenerated() deve ser chamado após AddProxos().\");");

        var seen = new HashSet<string>();

        foreach (var info in handlers)
        {
            foreach (var entry in info.Entries)
            {
                // DI registration (evita duplicatas)
                var key = $"{entry.HandlerType}::{entry.InterfaceType}";
                if (seen.Add(key))
                {
                    sb.AppendLine($"        services.AddScoped<global::{entry.InterfaceType}, global::{entry.HandlerType}>();");
                }

                // WrapperRegistry registration
                switch (entry.Kind)
                {
                    case HandlerKind.Request:
                        var regKey = $"REQ::{entry.TypeArg1}::{entry.TypeArg2}";
                        if (seen.Add(regKey))
                        {
                            sb.AppendLine($"        global::Proxos.ProxosRegistrar.RegisterRequest<global::{entry.TypeArg1}, global::{entry.TypeArg2}>(wrapperRegistry);");
                        }
                        break;

                    case HandlerKind.Notification:
                        var notifKey = $"NOTIF::{entry.TypeArg1}";
                        if (seen.Add(notifKey))
                        {
                            sb.AppendLine($"        global::Proxos.ProxosRegistrar.RegisterNotification<global::{entry.TypeArg1}>(wrapperRegistry);");
                        }
                        break;

                    case HandlerKind.Stream:
                        var streamKey = $"STREAM::{entry.TypeArg1}::{entry.TypeArg2}";
                        if (seen.Add(streamKey))
                        {
                            sb.AppendLine($"        global::Proxos.ProxosRegistrar.RegisterStream<global::{entry.TypeArg1}, global::{entry.TypeArg2}>(wrapperRegistry);");
                        }
                        break;
                }
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("ProxosGeneratedExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private enum HandlerKind { Request, Notification, Stream }

    private sealed class HandlerEntry
    {
        public HandlerKind Kind { get; }
        public string HandlerType { get; }
        public string InterfaceType { get; }
        public string TypeArg1 { get; }
        public string? TypeArg2 { get; }

        public HandlerEntry(HandlerKind kind, string handlerType, string interfaceType,
            string typeArg1, string? typeArg2)
        {
            Kind = kind;
            HandlerType = handlerType;
            InterfaceType = interfaceType;
            TypeArg1 = typeArg1;
            TypeArg2 = typeArg2;
        }
    }

    private sealed class HandlerInfo
    {
        public string TypeName { get; }
        public List<HandlerEntry> Entries { get; }

        public HandlerInfo(string typeName, List<HandlerEntry> entries)
        {
            TypeName = typeName;
            Entries = entries;
        }
    }
}
